FROM ubuntu

RUN echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until
	
RUN apt-get update && apt-get install -y \
    openssh-server \
    gdb \
	git \
	pkg-config \
    g++ rsync zip make cmake ninja-build \
    libboost-dev \
    flatbuffers-compiler libflatbuffers1 libflatbuffers-dev
	
RUN git clone https://github.com/pocoproject/poco.git && cd poco && git checkout  poco-1.11.0-release && make install

ENV CMAKE_C_COMPILER=/usr/bin/gcc
ENV CMAKE_CXX_COMPILER=/usr/bin/g++
ENV CMAKE_MAKE_PROGRAM=/usr/bin/ninja

# Configure SSH
RUN mkdir -p /var/run/sshd
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && ssh-keygen -A

# Add user and set password
RUN useradd -m -d /home/dev -s /bin/bash -G sudo dev && echo "dev:dev" | chpasswd

# Expose port 22
EXPOSE 22

ENTRYPOINT service ssh restart && bash
